### ISSUE TITLE
Add languages to SDK

### ISSUE THREAD

**Issue by Sevitas** [Kentico/kontent-delivery-sdk-php#96] opened 2021-01-13 15:34 UTC
### Motivation

Why is this feature required? What problems does it solve?

### Proposed solution

An ideal solution for the above problems.

### Additional context

Add any other context, screenshots, or reference links about the feature request here.

**Comment by Simply007** [comment] 2021-01-13 15:51
I guess duplicate of #95

**Closed** 2021-01-13 15:53 UTC
